#title in header
title: "Damali Boyd"

#main info
#owner
owner: "I am Damali"
#email: test@test.test
info: "A software engineer and artist from Southeastern United States."
#description
desc: "Welcome to my little corner of the internet. Most post will be about programming and art. In addition to that, I am also learning philosophy, rhetoric, and working on my analytical skills so there will be posts about that as well."

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 326273

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
#usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink:
github: https://github.com/damaliboyd
linkedin:
twitter:
instagram:

# Misc
nanobar: /js/nanobar.min.js
switch_light: ⬜
switch_dark: ⬛

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
